import { ScoutedPlayer } from '../types';

export const INITIAL_FICHAJES: ScoutedPlayer[] = [
  {
    id: 'fich_2026_01',
    nombre: 'Iker Alday',
    equipo: 'Real Avilés Industrial',
    categoria: 'Primera RFEF',
    posicion: 'Lateral Derecho',
    anoNacimiento: 2003,
    lateralidad: 'Diestro',
    valorMercado: 280000,
    calificacion: 4,
    notas: 'Lateral derecho con excelentes coberturas defensivas, agresivo al corte y con buen posicionamiento posicional en repliegues.',
    atributos: { fisico: 7, tecnica: 6, tactica: 8, mental: 8 },
    fechaRegistro: '2026-06-28',
    altura: '1.81 m',
    esFichajeVerano2026: true,
    fichajeFecha: '2026-07-01',
    fichajeDetalles: 'Libre',
    fichajeOrigen: 'SD Eibar',
    fotoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    recomendacion: 'SEGUIR',
    recomendacionComentario: 'Buen perfil joven para alternar en el lateral derecho.',
    descripcionGeneral: 'Lateral derecho con gran proyección defensiva e intensidad.',
    fortalezas: 'Excelente marca.\nVelocidad en repliegue.\nBuen juego aéreo.',
    debilidades: 'Proyección ofensiva limitada.\nCentros en carrera.'
  },
  {
    id: 'fich_2026_02',
    nombre: 'Pitu Doncel',
    equipo: 'Real Avilés Industrial',
    categoria: 'Primera RFEF',
    posicion: 'Mediapunta',
    anoNacimiento: 1998,
    lateralidad: 'Zurdo',
    valorMercado: 220000,
    calificacion: 4,
    notas: 'Extremo polivalente, veloz, con buen uno contra uno y facilidad para asistir desde línea de fondo.',
    atributos: { fisico: 7, tecnica: 8, tactica: 7, mental: 7 },
    fechaRegistro: '2026-06-28',
    altura: '1.75 m',
    esFichajeVerano2026: true,
    fichajeFecha: '2026-07-01',
    fichajeDetalles: 'Libre',
    fichajeOrigen: 'CF Talavera',
    fotoUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    recomendacion: 'FIRMAR',
    recomendacionComentario: 'Extremo dinámico ideal para dotar al ataque de desborde exterior.',
    descripcionGeneral: 'Jugador veloz con magnífica pierna izquierda.',
    fortalezas: 'Regate en velocidad.\nCentros precisos.\nAsistencia.',
    debilidades: 'Menor aportación en fase de repliegue defensivo.'
  },
  {
    id: 'fich_2026_03',
    nombre: 'Jon Sillero',
    equipo: 'Real Avilés Industrial',
    categoria: 'Primera RFEF',
    posicion: 'Defensa Central',
    anoNacimiento: 1998,
    lateralidad: 'Diestro',
    valorMercado: 180000,
    calificacion: 4,
    notas: 'Central sobrio y contundente, excelente en anticipación y salida de balón rasa.',
    atributos: { fisico: 8, tecnica: 7, tactica: 8, mental: 7 },
    fechaRegistro: '2026-06-28',
    altura: '1.84 m',
    esFichajeVerano2026: true,
    fichajeFecha: '2026-07-01',
    fichajeDetalles: 'Libre',
    fichajeOrigen: 'Arenas Club',
    fotoUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
    recomendacion: 'FIRMAR',
    recomendacionComentario: 'Central contrastado que aportará experiencia y solvencia inmediata.',
    descripcionGeneral: 'Defensa central muy contundente y veloz al cruce.',
    fortalezas: 'Anticipación.\nJuego aéreo.\nLiderazgo vocal.',
    debilidades: 'Gira lento ante delanteros ágiles.'
  },
  {
    id: 'fich_2026_04',
    nombre: 'Markel Artetxe',
    equipo: 'Real Avilés Industrial',
    categoria: 'Primera RFEF',
    posicion: 'Defensa Central',
    anoNacimiento: 1999,
    lateralidad: 'Diestro',
    valorMercado: 150000,
    calificacion: 3.5,
    notas: 'Defensa central joven con buena colocación, rápido en anticipaciones y seguro en coberturas por banda.',
    atributos: { fisico: 7, tecnica: 6, tactica: 7, mental: 7 },
    fechaRegistro: '2026-06-28',
    altura: '1.83 m',
    esFichajeVerano2026: true,
    fichajeFecha: '2026-06-27',
    fichajeDetalles: 'Libre',
    fichajeOrigen: 'Racing Ferrol',
    fotoUrl: 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?w=150&auto=format&fit=crop&q=80',
    recomendacion: 'SEGUIR',
    recomendacionComentario: 'Central de gran porvenir con madurez superior para su edad.',
    descripcionGeneral: 'Defensa fiable con gran capacidad de aprendizaje.',
    fortalezas: 'Lectura defensiva.\nSalida de balón.\nTiro libre indirecto.',
    debilidades: 'Duelos cuerpo a cuerpo con delanteros corpulentos.'
  },
  {
    id: 'fich_2026_05',
    nombre: 'Samu Mayo',
    equipo: 'Real Avilés Industrial',
    categoria: 'Primera RFEF',
    posicion: 'Mediocentro',
    anoNacimiento: 2001,
    lateralidad: 'Diestro',
    valorMercado: 240000,
    calificacion: 4,
    notas: 'Mediocentro organizador de gran lectura, excelente distribución de balón y buen robo posicional.',
    atributos: { fisico: 7, tecnica: 8, tactica: 8, mental: 8 },
    fechaRegistro: '2026-06-28',
    altura: '1.80 m',
    esFichajeVerano2026: true,
    fichajeFecha: '2026-07-01',
    fichajeDetalles: 'Libre',
    fichajeOrigen: 'CD Guadalajara',
    fotoUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    recomendacion: 'FIRMAR',
    recomendacionComentario: 'Motor del mediocampo con gran presente y excelente proyección.',
    descripcionGeneral: 'Mediocentro completo que maneja el ritmo del juego.',
    fortalezas: 'Visión de juego.\nPase largo y corto.\nInterceptación.',
    debilidades: 'Poca llegada al área rival.'
  },
  {
    id: 'fich_2026_06',
    nombre: 'Cris Montes',
    equipo: 'Real Avilés Industrial',
    categoria: 'Primera RFEF',
    posicion: 'Extremo Derecho',
    anoNacimiento: 1998,
    lateralidad: 'Zurdo',
    valorMercado: 300000,
    calificacion: 5,
    notas: 'Extremo con regate desequilibrante hacia dentro, disparo de media distancia sensacional y gran fantasía en el pase final.',
    atributos: { fisico: 7, tecnica: 9, tactica: 8, mental: 8 },
    fechaRegistro: '2026-06-28',
    altura: '1.72 m',
    esFichajeVerano2026: true,
    fichajeFecha: '2026-06-28',
    fichajeDetalles: 'Libre',
    fichajeOrigen: 'CD Tenerife',
    fotoUrl: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=150&auto=format&fit=crop&q=80',
    recomendacion: 'FIRMAR',
    recomendacionComentario: 'Fichaje estrella para la parcela ofensiva. Calidad diferencial para Primera RFEF.',
    descripcionGeneral: 'Jugador diferencial capaz de resolver partidos por sí solo.',
    fortalezas: 'Disparo de rosca.\nAsistencias entre líneas.\nRegate.',
    debilidades: 'Menor rigurosidad defensiva.'
  },
  {
    id: 'fich_2026_07',
    nombre: 'Álvaro Ratón',
    equipo: 'Real Avilés Industrial',
    categoria: 'Primera RFEF',
    posicion: 'Portero',
    anoNacimiento: 1993,
    lateralidad: 'Zurdo',
    valorMercado: 250000,
    calificacion: 4,
    notas: 'Portero de gran envergadura y excelentes reflejos. Experto bajo palos con buen dominio del área.',
    atributos: { fisico: 7, tecnica: 7, tactica: 8, mental: 8 },
    fechaRegistro: '2026-06-28',
    altura: '1.92 m',
    esFichajeVerano2026: true,
    fichajeFecha: '2026-06-29',
    fichajeDetalles: 'Libre',
    fichajeOrigen: 'Ourense',
    fotoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    recomendacion: 'FIRMAR',
    recomendacionComentario: 'Garantía absoluta para la portería, con experiencia en ligas superiores.',
    descripcionGeneral: 'Guardameta sobrio, líder indiscutible en defensa.',
    fortalezas: 'Seguridad bajo palos.\nJuego aéreo.\nColocación.',
    debilidades: 'Precisión con el pie bajo presión.'
  },
  {
    id: 'fich_2026_08',
    nombre: 'Marco Suárez',
    equipo: 'Real Avilés Industrial',
    categoria: 'Primera RFEF',
    posicion: 'Portero',
    anoNacimiento: 2004,
    lateralidad: 'Zurdo',
    valorMercado: 130000,
    calificacion: 3.5,
    notas: 'Guardameta joven de gran proyección procedente de la cantera de Unionistas.',
    atributos: { fisico: 8, tecnica: 6, tactica: 7, mental: 7 },
    fechaRegistro: '2026-06-28',
    altura: '1.87 m',
    esFichajeVerano2026: true,
    fichajeFecha: '2026-06-27',
    fichajeDetalles: 'Libre',
    fichajeOrigen: 'Unionistas CF',
    fotoUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
    recomendacion: 'SEGUIR',
    recomendacionComentario: 'Interesante portero de rotación con proyección de futuro.',
    descripcionGeneral: 'Portero ágil con buen juego aéreo y reflejos felinos.',
    fortalezas: 'Velocidad de reacción.\nDominio del área.\nLanzamiento con la mano.',
    debilidades: 'Toma de decisiones bajo presión.'
  },
  {
    id: 'fich_2026_09',
    nombre: 'Pablo Álvarez',
    equipo: 'Real Avilés Industrial',
    categoria: 'Primera RFEF',
    posicion: 'Mediapunta',
    anoNacimiento: 2004,
    lateralidad: 'Diestro',
    valorMercado: 120000,
    calificacion: 3,
    notas: 'Mediocentro ofensivo / mediapunta de gran talento técnico, buen último pase y regreso de cesión.',
    atributos: { fisico: 6, tecnica: 8, tactica: 7, mental: 7 },
    fechaRegistro: '2026-06-28',
    altura: '1.78 m',
    esFichajeVerano2026: true,
    fichajeFecha: '2026-06-30',
    fichajeDetalles: 'Fin de cesión (30/06/2026)',
    fichajeOrigen: 'CD Numancia',
    fotoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    recomendacion: 'SEGUIR',
    recomendacionComentario: 'Regresa tras cesión, evaluar potencial de minutos en la plantilla.',
    descripcionGeneral: 'Mediapunta con exquisita técnica individual.',
    fortalezas: 'Visión de juego.\nÚltimo pase.\nConducción.',
    debilidades: 'Aportación defensiva y resistencia.'
  }
];
